server:
  port: 8080
  servlet.context-path: /

spring:
  application:
    name: estoque-service

br.com.rocknewventures.estoqueservice.config:
  webservice:
    location-uri: /ws
    xsd-schema: xsd/estoque.xsd
    wsdl-definition:
      port-name: EstoquePort
      service-name: EstoqueService
      target-namespace: http://rocknewventures.com.br/estoque