server:
  port: 8080
  servlet.context-path: /

spring:
  application:
    name: pedido-service

br.com.rocknewventures.pedidoservice.config:
  webservice:
    location-uri: /ws
    xsd-schema: xsd/pedido.xsd
    wsdl-definition:
      port-name: PedidoPort
      service-name: PedidoService
      target-namespace: http://rocknewventures.com.br/pedidos
